[package]
name = "vmix_rs"
version = "0.1.0"
edition = "2021"

authors = ["Shugo Kawamura <ruk1ium@gmail.com>"]
repository = "https://github.com/FlowingSPDG/vmix-rs"
license = "MIT"
description = "vMix HTTP/TCP API Library"

[dependencies]
anyhow = "1.0.69"
serde = { version = "1.0.152", features = ["derive"] }
quick-xml = { version = "0.34", features = ["serialize"] }
tokio = { version = "1.25.0", features = ["rt", "net", "sync", "macros", "rt-multi-thread", "io-util", "io-std", "time", "signal"] }
urlencoding = "2.1.3"
reqwest = { version = "0.11", features = ["json"] }
async-trait = "0.1"

[dev-dependencies]
